name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/eclipse-ankaios/app-ankaios-dev:0.2.0-rc1
      options: --user root

    steps:
      - run: apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git jq
          version: 1.0
      - name: install yq
        run: |
          curl -sL https://objects.githubusercontent.com/github-production-release-asset-2e65be/43225113/fb29f93d-2582-4ef2-90f7-bec4d2a549c6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231128%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231128T143413Z&X-Amz-Expires=300&X-Amz-Signature=9b63e53c88228e265bd10c3faaee1037787731826690b96ad06b2f8d99aec3d7&X-Amz-SignedHeaders=host&actor_id=1366654&key_id=0&repo_id=43225113&response-content-disposition=attachment%3B%20filename%3Dyq_linux_amd64&response-content-type=application%2Foctet-stream -o /usr/bin/yq \
          chmod +x /usr/bin/yq
      - name: Tweak git config
        run: |
          git config --global --add safe.directory '*'
          echo "if [ -f /etc/bash_completion ] && ! shopt -oq posix; then\n . /etc/bash_completion \nfi" >> /root/.bashrc
          echo 'export PATH=$PATH:/workspaces/app/scripts:/workspaces/app/in-vehicle-stack/scenarios/smart_trailer_use_case/scripts' >> /root/.bashrc
      - run: mkdir /tmp/logs
      - name: Start Ankaios
        run: eclipse-ankaios/scripts/run_maestro.sh > /tmp/logs/run_maestro.log &
      - name: Start trailer applications
        run: scenarios/smart_trailer_use_case/scripts/start_trailer_applications_ankaios.sh > /tmp/logs/start_trailer_applications_ankaios.log &
      - name: Connect trailer
        run: |
          cd scenarios/smart_trailer_use_case/digital_twin_providers/trailer_connected_provider
          podman build -t trailer-connected .
          podman run -d -p 4020:4020 my-image-name
      - name: Output logs
        run: tail -f /tmp/logs/*.log

