name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/eclipse-ankaios/app-ankaios-dev:0.2.0-rc1
      options: --user root

    steps:
      - run: apt-get update
      - run: apt-get install -y git jq
      - name: install yq
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${TARGETARCH} -o /usr/bin/yq -o /usr/bin/yq
          chmod +x /usr/bin/yq
      - name: Tweak git config
        run: |
          git config --global --add safe.directory '*'
          echo "if [ -f /etc/bash_completion ] && ! shopt -oq posix; then\n . /etc/bash_completion \nfi" >> /root/.bashrc
          echo 'export PATH=$PATH:/workspaces/app/scripts:/workspaces/app/in-vehicle-stack/scenarios/smart_trailer_use_case/scripts' >> /root/.bashrc
      - run: mkdir /tmp/logs
      - name: Start Ankaios
        run: eclipse-ankaios/scripts/run_maestro.sh > /tmp/logs/run_maestro.log &
      - name: Start trailer applications
        run: scenarios/smart_trailer_use_case/scripts/start_trailer_applications_ankaios.sh > /tmp/logs/start_trailer_applications_ankaios.log &
      - name: Connect trailer
        run: |
          cd scenarios/smart_trailer_use_case/digital_twin_providers/trailer_connected_provider
          podman build -t trailer-connected .
          podman run -d -p 4020:4020 my-image-name
      - name: Output logs
        run: tail -f /tmp/logs/*.log

